baseURL = "https://www.milan.bio"
languageCode = "en-us"
theme = "PaperMod"
title = "Milan Stevanović"
googleAnalytics = "G-41F4SC2GG7"
enableRobotsTXT = true

[pagination]
pagerSize = 10

[markup.goldmark.renderer]
unsafe = true

[params]
# Theme mode
defaultTheme = "auto"
disableThemeToggle = false

# Homepage configuration
[params.profileMode]
enabled = false

# Features
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true
TocOpen = false

# SEO
ShowRssButtonInSectionTermList = true
UseHugoToc = true

# Homepage content
[params.homeInfoParams]
Title = "Milan Stevanović"
Content = """
Co-Founder & CTO building mindfulness technology

10+ years across engineering, product, and leadership roles in fintech and mobile development.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/milanstevanovic"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/milanstevanovic"

[[params.socialIcons]]
name = "email"
url = "mailto:hello@milan.bio"

[languages]
[languages.en]
  title = "Milan Stevanović"
  subtitle = "Senior Software Engineer & Product Manager"
  keywords = "software engineer, product manager, iOS, kotlin multiplatform, mobile development"
  copyright = "© 2025 Milan Stevanović"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "My Journey"
      url = "/posts/"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "services"
      name = "Services"
      url = "/services/"
      weight = 20
    [[languages.en.menu.main]]
      identifier = "cv"
      name = "CV"
      url = "/cv/"
      weight = 30
    [[languages.en.menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 40
    [[languages.en.menu.main]]
      identifier = "search"
      name = "Search"
      url = "/search/"
      weight = 50