baseURL = "https://www.milan.bio"
languageCode = "en-us"
theme = "terminal"
title = "Milan Stevanović"
googleAnalytics = "G-41F4SC2GG7"
enableRobotsTXT = true

[pagination]
pagerSize = 10

[markup.goldmark.renderer]
unsafe = true

[params]
contentTypeName = "posts"
showMenuItems = 4
fullWidthTheme = false
centerTheme = false

[languages]
[languages.en]
  title = "Milan Stevanović"
  subtitle = "Senior Software Engineer & Product Manager"
  keywords = "software engineer, product manager, iOS, kotlin multiplatform, mobile development"
  copyright = "© 2025 Milan Stevanović"
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"

  [languages.en.params.logo]
    logoText = "milan.bio"
    logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "journey"
      name = "My Journey"
      url = "/"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "services"
      name = "Services"
      url = "/services/"
      weight = 20
    [[languages.en.menu.main]]
      identifier = "cv"
      name = "CV"
      url = "/cv/"
      weight = 30
    [[languages.en.menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 40